[package]
name = "jmespath-streaming"
version = "0.0.1"
authors = ["Michael Dowling <mtdowling@gmail.com>"]
license = "MIT"

[dependencies]
serde = "^0.7"
serde_json = "^0.7"

[dependencies.jmespath]
path = ".."
version = "*"
